//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraReports.EXTRA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectionSet", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectionSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblToAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intColField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAMFMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMerzeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMpoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strStartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblToAmt {
            get {
                return this.dblToAmtField;
            }
            set {
                if ((this.dblToAmtField.Equals(value) != true)) {
                    this.dblToAmtField = value;
                    this.RaisePropertyChanged("dblToAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCol {
            get {
                return this.intColField;
            }
            set {
                if ((this.intColField.Equals(value) != true)) {
                    this.intColField = value;
                    this.RaisePropertyChanged("intCol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intRow {
            get {
                return this.intRowField;
            }
            set {
                if ((this.intRowField.Equals(value) != true)) {
                    this.intRowField = value;
                    this.RaisePropertyChanged("intRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intSerial {
            get {
                return this.intSerialField;
            }
            set {
                if ((this.intSerialField.Equals(value) != true)) {
                    this.intSerialField = value;
                    this.RaisePropertyChanged("intSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strAMFM {
            get {
                return this.strAMFMField;
            }
            set {
                if ((object.ReferenceEquals(this.strAMFMField, value) != true)) {
                    this.strAMFMField = value;
                    this.RaisePropertyChanged("strAMFM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strEndDate {
            get {
                return this.strEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strEndDateField, value) != true)) {
                    this.strEndDateField = value;
                    this.RaisePropertyChanged("strEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMerzeName {
            get {
                return this.strMerzeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strMerzeNameField, value) != true)) {
                    this.strMerzeNameField = value;
                    this.RaisePropertyChanged("strMerzeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMpoName {
            get {
                return this.strMpoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strMpoNameField, value) != true)) {
                    this.strMpoNameField = value;
                    this.RaisePropertyChanged("strMpoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionDate {
            get {
                return this.strProjectionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionDateField, value) != true)) {
                    this.strProjectionDateField = value;
                    this.RaisePropertyChanged("strProjectionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionKey {
            get {
                return this.strProjectionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionKeyField, value) != true)) {
                    this.strProjectionKeyField = value;
                    this.RaisePropertyChanged("strProjectionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionName {
            get {
                return this.strProjectionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionNameField, value) != true)) {
                    this.strProjectionNameField = value;
                    this.RaisePropertyChanged("strProjectionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strStartDate {
            get {
                return this.strStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strStartDateField, value) != true)) {
                    this.strStartDateField = value;
                    this.RaisePropertyChanged("strStartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectonMonthConfig", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectonMonthConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lngTotalAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lngTotalLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strGRNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intSerial {
            get {
                return this.intSerialField;
            }
            set {
                if ((this.intSerialField.Equals(value) != true)) {
                    this.intSerialField = value;
                    this.RaisePropertyChanged("intSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lngTotalArea {
            get {
                return this.lngTotalAreaField;
            }
            set {
                if ((this.lngTotalAreaField.Equals(value) != true)) {
                    this.lngTotalAreaField = value;
                    this.RaisePropertyChanged("lngTotalArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lngTotalLedger {
            get {
                return this.lngTotalLedgerField;
            }
            set {
                if ((this.lngTotalLedgerField.Equals(value) != true)) {
                    this.lngTotalLedgerField = value;
                    this.RaisePropertyChanged("lngTotalLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFromDate {
            get {
                return this.strFromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strFromDateField, value) != true)) {
                    this.strFromDateField = value;
                    this.RaisePropertyChanged("strFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strGRName {
            get {
                return this.strGRNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strGRNameField, value) != true)) {
                    this.strGRNameField = value;
                    this.RaisePropertyChanged("strGRName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strStatus {
            get {
                return this.strStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.strStatusField, value) != true)) {
                    this.strStatusField = value;
                    this.RaisePropertyChanged("strStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strToDate {
            get {
                return this.strToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strToDateField, value) != true)) {
                    this.strToDateField = value;
                    this.RaisePropertyChanged("strToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mprojection", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class Mprojection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double APRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AUGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FRBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JULField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MAYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NOVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblUp_toDate_amntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strGRNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLedgerNameMerzeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strParticularsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double APR {
            get {
                return this.APRField;
            }
            set {
                if ((this.APRField.Equals(value) != true)) {
                    this.APRField = value;
                    this.RaisePropertyChanged("APR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AUG {
            get {
                return this.AUGField;
            }
            set {
                if ((this.AUGField.Equals(value) != true)) {
                    this.AUGField = value;
                    this.RaisePropertyChanged("AUG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DEC {
            get {
                return this.DECField;
            }
            set {
                if ((this.DECField.Equals(value) != true)) {
                    this.DECField = value;
                    this.RaisePropertyChanged("DEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FRB {
            get {
                return this.FRBField;
            }
            set {
                if ((this.FRBField.Equals(value) != true)) {
                    this.FRBField = value;
                    this.RaisePropertyChanged("FRB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JAN {
            get {
                return this.JANField;
            }
            set {
                if ((this.JANField.Equals(value) != true)) {
                    this.JANField = value;
                    this.RaisePropertyChanged("JAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JUL {
            get {
                return this.JULField;
            }
            set {
                if ((this.JULField.Equals(value) != true)) {
                    this.JULField = value;
                    this.RaisePropertyChanged("JUL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JUN {
            get {
                return this.JUNField;
            }
            set {
                if ((this.JUNField.Equals(value) != true)) {
                    this.JUNField = value;
                    this.RaisePropertyChanged("JUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MAR {
            get {
                return this.MARField;
            }
            set {
                if ((this.MARField.Equals(value) != true)) {
                    this.MARField = value;
                    this.RaisePropertyChanged("MAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MAY {
            get {
                return this.MAYField;
            }
            set {
                if ((this.MAYField.Equals(value) != true)) {
                    this.MAYField = value;
                    this.RaisePropertyChanged("MAY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NOV {
            get {
                return this.NOVField;
            }
            set {
                if ((this.NOVField.Equals(value) != true)) {
                    this.NOVField = value;
                    this.RaisePropertyChanged("NOV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OCT {
            get {
                return this.OCTField;
            }
            set {
                if ((this.OCTField.Equals(value) != true)) {
                    this.OCTField = value;
                    this.RaisePropertyChanged("OCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SEP {
            get {
                return this.SEPField;
            }
            set {
                if ((this.SEPField.Equals(value) != true)) {
                    this.SEPField = value;
                    this.RaisePropertyChanged("SEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblBalance {
            get {
                return this.dblBalanceField;
            }
            set {
                if ((this.dblBalanceField.Equals(value) != true)) {
                    this.dblBalanceField = value;
                    this.RaisePropertyChanged("dblBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblUp_toDate_amnt {
            get {
                return this.dblUp_toDate_amntField;
            }
            set {
                if ((this.dblUp_toDate_amntField.Equals(value) != true)) {
                    this.dblUp_toDate_amntField = value;
                    this.RaisePropertyChanged("dblUp_toDate_amnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intMode {
            get {
                return this.intModeField;
            }
            set {
                if ((this.intModeField.Equals(value) != true)) {
                    this.intModeField = value;
                    this.RaisePropertyChanged("intMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strGRName {
            get {
                return this.strGRNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strGRNameField, value) != true)) {
                    this.strGRNameField = value;
                    this.RaisePropertyChanged("strGRName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLedgerNameMerze {
            get {
                return this.strLedgerNameMerzeField;
            }
            set {
                if ((object.ReferenceEquals(this.strLedgerNameMerzeField, value) != true)) {
                    this.strLedgerNameMerzeField = value;
                    this.RaisePropertyChanged("strLedgerNameMerze");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strParticulars {
            get {
                return this.strParticularsField;
            }
            set {
                if ((object.ReferenceEquals(this.strParticularsField, value) != true)) {
                    this.strParticularsField = value;
                    this.RaisePropertyChanged("strParticulars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PCollectionCopmarison", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class PCollectionCopmarison : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLastMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLedgerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double strMonthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthNameeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strstrDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblAmount {
            get {
                return this.dblAmountField;
            }
            set {
                if ((this.dblAmountField.Equals(value) != true)) {
                    this.dblAmountField = value;
                    this.RaisePropertyChanged("dblAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strEndDate {
            get {
                return this.strEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strEndDateField, value) != true)) {
                    this.strEndDateField = value;
                    this.RaisePropertyChanged("strEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLastMonth {
            get {
                return this.strLastMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.strLastMonthField, value) != true)) {
                    this.strLastMonthField = value;
                    this.RaisePropertyChanged("strLastMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLedgerName {
            get {
                return this.strLedgerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strLedgerNameField, value) != true)) {
                    this.strLedgerNameField = value;
                    this.RaisePropertyChanged("strLedgerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double strMonthName {
            get {
                return this.strMonthNameField;
            }
            set {
                if ((this.strMonthNameField.Equals(value) != true)) {
                    this.strMonthNameField = value;
                    this.RaisePropertyChanged("strMonthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthNamee {
            get {
                return this.strMonthNameeField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthNameeField, value) != true)) {
                    this.strMonthNameeField = value;
                    this.RaisePropertyChanged("strMonthNamee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionName {
            get {
                return this.strProjectionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionNameField, value) != true)) {
                    this.strProjectionNameField = value;
                    this.RaisePropertyChanged("strProjectionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strstrDate {
            get {
                return this.strstrDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strstrDateField, value) != true)) {
                    this.strstrDateField = value;
                    this.RaisePropertyChanged("strstrDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EXTRA.ISWPRJ")]
    public interface ISWPRJ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionList", ReplyAction="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionListResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillWeeklyProjectionList(string strDeComID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mDeleteWeeklyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mDeleteWeeklyProjectionResponse")]
        string mDeleteWeeklyProjection(string strDeComID, string strMonthID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjectionResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjection(string strDeComID, string strMonthID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeekly", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeeklyResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeekly(string strDeComID, string strKey, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertWeeklyProjectionSet", ReplyAction="http://tempuri.org/ISWPRJ/mInsertWeeklyProjectionSetResponse")]
        string mInsertWeeklyProjectionSet(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, double dblWrittenAmount, int intDel, int intCols, int intRow, string strCommProjectionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/getZoneFromDivsion", ReplyAction="http://tempuri.org/ISWPRJ/getZoneFromDivsionResponse")]
        ExtraReports.EXTRA.ProjectonMonthConfig[] getZoneFromDivsion(string strDeComID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMpoPerformance", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMpoPerformanceResponse")]
        string mInsertMpoPerformance(string strDeComID, string strLedgerName, string strFdate, string strTdate, int intmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mQueryPerformance", ReplyAction="http://tempuri.org/ISWPRJ/mQueryPerformanceResponse")]
        ExtraReports.EXTRA.Mprojection[] mQueryPerformance(string strDeComID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetLedgerGroupLoad", ReplyAction="http://tempuri.org/ISWPRJ/mGetLedgerGroupLoadResponse")]
        ExtraReports.EXTRA.Mprojection[] mGetLedgerGroupLoad(string strDeComID, int intMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMonthConfigResponse")]
        string mInsertMonthConfig(string strDeComID, string strMonthID, string strMonthFromDate, string strMonthToDate, int intStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthConfigResponse")]
        ExtraReports.EXTRA.ProjectonMonthConfig[] mFillMonthConfig(string strDeComID, int intStaus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/DeletetMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/DeletetMonthConfigResponse")]
        string DeletetMonthConfig(string strDeComID, int intSerialkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mUpdateMonthConfigpublic", ReplyAction="http://tempuri.org/ISWPRJ/mUpdateMonthConfigpublicResponse")]
        string mUpdateMonthConfigpublic(string strDeComID, string strMonthID, string strFromDate, string strToDate, int intStatus, int intSerialKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertProjectionSetup", ReplyAction="http://tempuri.org/ISWPRJ/mInsertProjectionSetupResponse")]
        string mInsertProjectionSetup(string strDeComID, string strMonthID, string DgGrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillPojictionConfig", ReplyAction="http://tempuri.org/ISWPRJ/mFillPojictionConfigResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillPojictionConfig(string strDeComID, string strMonthID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/DeletetProjectionSetUp", ReplyAction="http://tempuri.org/ISWPRJ/DeletetProjectionSetUpResponse")]
        string DeletetProjectionSetUp(string strDeComID, string strProjectionkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mUpdateProjectionSetup", ReplyAction="http://tempuri.org/ISWPRJ/mUpdateProjectionSetupResponse")]
        string mUpdateProjectionSetup(string strDeComID, string strMonthID, string DgGrid, string strProjectionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjection(string strDeComID, string strProjectionMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionLedger", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionLedgerResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjectionLedger(string strDeComID, string strLedgerGroup, string strMonthID, int intmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMonthlyProjectionResponse")]
        string mInsertMonthlyProjection(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, int intDel, int intCols, int intRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionList", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionListResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjectionList(string strDeComID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjectionResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayLedgerName", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameResponse")]
        ExtraReports.EXTRA.ProjectionSet[] mFillDisplayLedgerName(string strDeComID, string strKey, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mDeleteMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mDeleteMonthlyProjectionResponse")]
        string mDeleteMonthlyProjection(string strDeComID, string strMonthID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/gCheckProjectionActive", ReplyAction="http://tempuri.org/ISWPRJ/gCheckProjectionActiveResponse")]
        string gCheckProjectionActive(string strDeComID, string strDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetMontlyLadgerProjection", ReplyAction="http://tempuri.org/ISWPRJ/mGetMontlyLadgerProjectionResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetMontlyLadgerProjection(string strDeComID, string strThisMonth, string strledger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetMontlyLadger", ReplyAction="http://tempuri.org/ISWPRJ/mGetMontlyLadgerResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetMontlyLadger(string strDeComID, string strThisMonth, string strledger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetCollectionComparision", ReplyAction="http://tempuri.org/ISWPRJ/mGetCollectionComparisionResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetCollectionComparision(string strDeComID, string strThisMonth, string strLastMont);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetProjectionStarEndDate", ReplyAction="http://tempuri.org/ISWPRJ/mGetProjectionStarEndDateResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetProjectionStarEndDate(string strDeComID, string strThisMonth, string strLastMont);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetCollectionComparisionReport", ReplyAction="http://tempuri.org/ISWPRJ/mGetCollectionComparisionReportResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetCollectionComparisionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetProjectionReport", ReplyAction="http://tempuri.org/ISWPRJ/mGetProjectionReportResponse")]
        ExtraReports.EXTRA.PCollectionCopmarison[] mGetProjectionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWPRJChannel : ExtraReports.EXTRA.ISWPRJ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWPRJClient : System.ServiceModel.ClientBase<ExtraReports.EXTRA.ISWPRJ>, ExtraReports.EXTRA.ISWPRJ {
        
        public SWPRJClient() {
        }
        
        public SWPRJClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWPRJClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPRJClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPRJClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillWeeklyProjectionList(string strDeComID) {
            return base.Channel.mFillWeeklyProjectionList(strDeComID);
        }
        
        public string mDeleteWeeklyProjection(string strDeComID, string strMonthID) {
            return base.Channel.mDeleteWeeklyProjection(strDeComID, strMonthID);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjection(string strDeComID, string strMonthID, string strDivision) {
            return base.Channel.mFillDisplayWeeklyProjection(strDeComID, strMonthID, strDivision);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeekly(string strDeComID, string strKey, string strDivision) {
            return base.Channel.mFillDisplayLedgerNameWeekly(strDeComID, strKey, strDivision);
        }
        
        public string mInsertWeeklyProjectionSet(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, double dblWrittenAmount, int intDel, int intCols, int intRow, string strCommProjectionName) {
            return base.Channel.mInsertWeeklyProjectionSet(strDeComID, strKey, strMonthID, strDivision, strBranchID, strLedgerName, strHeadName, dblAmount, dblWrittenAmount, intDel, intCols, intRow, strCommProjectionName);
        }
        
        public ExtraReports.EXTRA.ProjectonMonthConfig[] getZoneFromDivsion(string strDeComID, string strDivision) {
            return base.Channel.getZoneFromDivsion(strDeComID, strDivision);
        }
        
        public string mInsertMpoPerformance(string strDeComID, string strLedgerName, string strFdate, string strTdate, int intmode) {
            return base.Channel.mInsertMpoPerformance(strDeComID, strLedgerName, strFdate, strTdate, intmode);
        }
        
        public ExtraReports.EXTRA.Mprojection[] mQueryPerformance(string strDeComID) {
            return base.Channel.mQueryPerformance(strDeComID);
        }
        
        public ExtraReports.EXTRA.Mprojection[] mGetLedgerGroupLoad(string strDeComID, int intMode) {
            return base.Channel.mGetLedgerGroupLoad(strDeComID, intMode);
        }
        
        public string mInsertMonthConfig(string strDeComID, string strMonthID, string strMonthFromDate, string strMonthToDate, int intStatus) {
            return base.Channel.mInsertMonthConfig(strDeComID, strMonthID, strMonthFromDate, strMonthToDate, intStatus);
        }
        
        public ExtraReports.EXTRA.ProjectonMonthConfig[] mFillMonthConfig(string strDeComID, int intStaus) {
            return base.Channel.mFillMonthConfig(strDeComID, intStaus);
        }
        
        public string DeletetMonthConfig(string strDeComID, int intSerialkey) {
            return base.Channel.DeletetMonthConfig(strDeComID, intSerialkey);
        }
        
        public string mUpdateMonthConfigpublic(string strDeComID, string strMonthID, string strFromDate, string strToDate, int intStatus, int intSerialKey) {
            return base.Channel.mUpdateMonthConfigpublic(strDeComID, strMonthID, strFromDate, strToDate, intStatus, intSerialKey);
        }
        
        public string mInsertProjectionSetup(string strDeComID, string strMonthID, string DgGrid) {
            return base.Channel.mInsertProjectionSetup(strDeComID, strMonthID, DgGrid);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillPojictionConfig(string strDeComID, string strMonthID) {
            return base.Channel.mFillPojictionConfig(strDeComID, strMonthID);
        }
        
        public string DeletetProjectionSetUp(string strDeComID, string strProjectionkey) {
            return base.Channel.DeletetProjectionSetUp(strDeComID, strProjectionkey);
        }
        
        public string mUpdateProjectionSetup(string strDeComID, string strMonthID, string DgGrid, string strProjectionKey) {
            return base.Channel.mUpdateProjectionSetup(strDeComID, strMonthID, DgGrid, strProjectionKey);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjection(string strDeComID, string strProjectionMonth) {
            return base.Channel.mFillMonthlyProjection(strDeComID, strProjectionMonth);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjectionLedger(string strDeComID, string strLedgerGroup, string strMonthID, int intmode) {
            return base.Channel.mFillMonthlyProjectionLedger(strDeComID, strLedgerGroup, strMonthID, intmode);
        }
        
        public string mInsertMonthlyProjection(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, int intDel, int intCols, int intRow) {
            return base.Channel.mInsertMonthlyProjection(strDeComID, strKey, strMonthID, strDivision, strBranchID, strLedgerName, strHeadName, dblAmount, intDel, intCols, intRow);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillMonthlyProjectionList(string strDeComID) {
            return base.Channel.mFillMonthlyProjectionList(strDeComID);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision) {
            return base.Channel.mFillDisplayMonthlyProjection(strDeComID, strMonthID, strDivision);
        }
        
        public ExtraReports.EXTRA.ProjectionSet[] mFillDisplayLedgerName(string strDeComID, string strKey, string strDivision) {
            return base.Channel.mFillDisplayLedgerName(strDeComID, strKey, strDivision);
        }
        
        public string mDeleteMonthlyProjection(string strDeComID, string strMonthID, string strDivision) {
            return base.Channel.mDeleteMonthlyProjection(strDeComID, strMonthID, strDivision);
        }
        
        public string gCheckProjectionActive(string strDeComID, string strDate) {
            return base.Channel.gCheckProjectionActive(strDeComID, strDate);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetMontlyLadgerProjection(string strDeComID, string strThisMonth, string strledger) {
            return base.Channel.mGetMontlyLadgerProjection(strDeComID, strThisMonth, strledger);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetMontlyLadger(string strDeComID, string strThisMonth, string strledger) {
            return base.Channel.mGetMontlyLadger(strDeComID, strThisMonth, strledger);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetCollectionComparision(string strDeComID, string strThisMonth, string strLastMont) {
            return base.Channel.mGetCollectionComparision(strDeComID, strThisMonth, strLastMont);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetProjectionStarEndDate(string strDeComID, string strThisMonth, string strLastMont) {
            return base.Channel.mGetProjectionStarEndDate(strDeComID, strThisMonth, strLastMont);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetCollectionComparisionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName) {
            return base.Channel.mGetCollectionComparisionReport(strDeComID, strProjectionName, strFromMonthID, strEndMonthID, intmode, strLedgerName);
        }
        
        public ExtraReports.EXTRA.PCollectionCopmarison[] mGetProjectionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName) {
            return base.Channel.mGetProjectionReport(strDeComID, strProjectionName, strFromMonthID, strEndMonthID, intmode, strLedgerName);
        }
    }
}
