//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.OTP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppsVercifysumm", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class AppsVercifysumm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.OTP.AppsVercify[] summaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.OTP.AppsVercify[] summary {
            get {
                return this.summaryField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryField, value) != true)) {
                    this.summaryField = value;
                    this.RaisePropertyChanged("summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppsVercify", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class AppsVercify : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intResult {
            get {
                return this.intResultField;
            }
            set {
                if ((this.intResultField.Equals(value) != true)) {
                    this.intResultField = value;
                    this.RaisePropertyChanged("intResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="summaryNew", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class summaryNew : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.OTP.details[] detailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.OTP.summary1[] summaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.OTP.details[] details {
            get {
                return this.detailsField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsField, value) != true)) {
                    this.detailsField = value;
                    this.RaisePropertyChanged("details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.OTP.summary1[] summary {
            get {
                return this.summaryField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryField, value) != true)) {
                    this.summaryField = value;
                    this.RaisePropertyChanged("summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="details", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doctorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double itemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double itemQuentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double itemTotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string slabgroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doctorName {
            get {
                return this.doctorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.doctorNameField, value) != true)) {
                    this.doctorNameField = value;
                    this.RaisePropertyChanged("doctorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.groupNameField, value) != true)) {
                    this.groupNameField = value;
                    this.RaisePropertyChanged("groupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.itemNameField, value) != true)) {
                    this.itemNameField = value;
                    this.RaisePropertyChanged("itemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double itemPrice {
            get {
                return this.itemPriceField;
            }
            set {
                if ((this.itemPriceField.Equals(value) != true)) {
                    this.itemPriceField = value;
                    this.RaisePropertyChanged("itemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double itemQuentity {
            get {
                return this.itemQuentityField;
            }
            set {
                if ((this.itemQuentityField.Equals(value) != true)) {
                    this.itemQuentityField = value;
                    this.RaisePropertyChanged("itemQuentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double itemTotalPrice {
            get {
                return this.itemTotalPriceField;
            }
            set {
                if ((this.itemTotalPriceField.Equals(value) != true)) {
                    this.itemTotalPriceField = value;
                    this.RaisePropertyChanged("itemTotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mpo {
            get {
                return this.mpoField;
            }
            set {
                if ((object.ReferenceEquals(this.mpoField, value) != true)) {
                    this.mpoField = value;
                    this.RaisePropertyChanged("mpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                if ((object.ReferenceEquals(this.orderidField, value) != true)) {
                    this.orderidField = value;
                    this.RaisePropertyChanged("orderid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string slabgroupName {
            get {
                return this.slabgroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.slabgroupNameField, value) != true)) {
                    this.slabgroupNameField = value;
                    this.RaisePropertyChanged("slabgroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="summary1", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class summary1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approveByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totlaQtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string approveBy {
            get {
                return this.approveByField;
            }
            set {
                if ((object.ReferenceEquals(this.approveByField, value) != true)) {
                    this.approveByField = value;
                    this.RaisePropertyChanged("approveBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string approveDate {
            get {
                return this.approveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.approveDateField, value) != true)) {
                    this.approveDateField = value;
                    this.RaisePropertyChanged("approveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doctor {
            get {
                return this.doctorField;
            }
            set {
                if ((object.ReferenceEquals(this.doctorField, value) != true)) {
                    this.doctorField = value;
                    this.RaisePropertyChanged("doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSelected {
            get {
                return this.isSelectedField;
            }
            set {
                if ((this.isSelectedField.Equals(value) != true)) {
                    this.isSelectedField = value;
                    this.RaisePropertyChanged("isSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mpo {
            get {
                return this.mpoField;
            }
            set {
                if ((object.ReferenceEquals(this.mpoField, value) != true)) {
                    this.mpoField = value;
                    this.RaisePropertyChanged("mpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.orderIdField, value) != true)) {
                    this.orderIdField = value;
                    this.RaisePropertyChanged("orderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                if ((this.totalAmountField.Equals(value) != true)) {
                    this.totalAmountField = value;
                    this.RaisePropertyChanged("totalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totlaQty {
            get {
                return this.totlaQtyField;
            }
            set {
                if ((this.totlaQtyField.Equals(value) != true)) {
                    this.totlaQtyField = value;
                    this.RaisePropertyChanged("totlaQty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MpoArea", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class MpoArea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMpoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMpoName {
            get {
                return this.strMpoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strMpoNameField, value) != true)) {
                    this.strMpoNameField = value;
                    this.RaisePropertyChanged("strMpoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTC {
            get {
                return this.strTCField;
            }
            set {
                if ((object.ReferenceEquals(this.strTCField, value) != true)) {
                    this.strTCField = value;
                    this.RaisePropertyChanged("strTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTName {
            get {
                return this.strTNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strTNameField, value) != true)) {
                    this.strTNameField = value;
                    this.RaisePropertyChanged("strTName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="notification", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblNetAmntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teritorrycodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblNetAmnt {
            get {
                return this.dblNetAmntField;
            }
            set {
                if ((this.dblNetAmntField.Equals(value) != true)) {
                    this.dblNetAmntField = value;
                    this.RaisePropertyChanged("dblNetAmnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                if ((object.ReferenceEquals(this.orderidField, value) != true)) {
                    this.orderidField = value;
                    this.RaisePropertyChanged("orderid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string teritorrycode {
            get {
                return this.teritorrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.teritorrycodeField, value) != true)) {
                    this.teritorrycodeField = value;
                    this.RaisePropertyChanged("teritorrycode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stockgroup", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class Stockgroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockItem", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class StockItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblClsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblClsBalance {
            get {
                return this.dblClsBalanceField;
            }
            set {
                if ((this.dblClsBalanceField.Equals(value) != true)) {
                    this.dblClsBalanceField = value;
                    this.RaisePropertyChanged("dblClsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strItemName {
            get {
                return this.strItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strItemNameField, value) != true)) {
                    this.strItemNameField = value;
                    this.RaisePropertyChanged("strItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUnit {
            get {
                return this.strUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.strUnitField, value) != true)) {
                    this.strUnitField = value;
                    this.RaisePropertyChanged("strUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MPO", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class MPO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intMpoTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lngUniqueNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLedgerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strSecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTeritorryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTeritorryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intMpoType {
            get {
                return this.intMpoTypeField;
            }
            set {
                if ((this.intMpoTypeField.Equals(value) != true)) {
                    this.intMpoTypeField = value;
                    this.RaisePropertyChanged("intMpoType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lngUniqueNo {
            get {
                return this.lngUniqueNoField;
            }
            set {
                if ((this.lngUniqueNoField.Equals(value) != true)) {
                    this.lngUniqueNoField = value;
                    this.RaisePropertyChanged("lngUniqueNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLedgerName {
            get {
                return this.strLedgerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strLedgerNameField, value) != true)) {
                    this.strLedgerNameField = value;
                    this.RaisePropertyChanged("strLedgerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMobileNo {
            get {
                return this.strMobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.strMobileNoField, value) != true)) {
                    this.strMobileNoField = value;
                    this.RaisePropertyChanged("strMobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strResponse {
            get {
                return this.strResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.strResponseField, value) != true)) {
                    this.strResponseField = value;
                    this.RaisePropertyChanged("strResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strSecurityCode {
            get {
                return this.strSecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.strSecurityCodeField, value) != true)) {
                    this.strSecurityCodeField = value;
                    this.RaisePropertyChanged("strSecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTeritorryCode {
            get {
                return this.strTeritorryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.strTeritorryCodeField, value) != true)) {
                    this.strTeritorryCodeField = value;
                    this.RaisePropertyChanged("strTeritorryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTeritorryName {
            get {
                return this.strTeritorryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strTeritorryNameField, value) != true)) {
                    this.strTeritorryNameField = value;
                    this.RaisePropertyChanged("strTeritorryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUserID {
            get {
                return this.strUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strUserIDField, value) != true)) {
                    this.strUserIDField = value;
                    this.RaisePropertyChanged("strUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUserPassword {
            get {
                return this.strUserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.strUserPasswordField, value) != true)) {
                    this.strUserPasswordField = value;
                    this.RaisePropertyChanged("strUserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCustomerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCustomerName {
            get {
                return this.strCustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strCustomerNameField, value) != true)) {
                    this.strCustomerNameField = value;
                    this.RaisePropertyChanged("strCustomerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockitemRate", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class StockitemRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commgroupgameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commgroupgame {
            get {
                return this.commgroupgameField;
            }
            set {
                if ((object.ReferenceEquals(this.commgroupgameField, value) != true)) {
                    this.commgroupgameField = value;
                    this.RaisePropertyChanged("commgroupgame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblRate {
            get {
                return this.dblRateField;
            }
            set {
                if ((this.dblRateField.Equals(value) != true)) {
                    this.dblRateField = value;
                    this.RaisePropertyChanged("dblRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.groupNameField, value) != true)) {
                    this.groupNameField = value;
                    this.RaisePropertyChanged("groupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.itemNameField, value) != true)) {
                    this.itemNameField = value;
                    this.RaisePropertyChanged("itemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commissionslab", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class Commissionslab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblFromRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblToRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblFromRange {
            get {
                return this.dblFromRangeField;
            }
            set {
                if ((this.dblFromRangeField.Equals(value) != true)) {
                    this.dblFromRangeField = value;
                    this.RaisePropertyChanged("dblFromRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblPercentage {
            get {
                return this.dblPercentageField;
            }
            set {
                if ((this.dblPercentageField.Equals(value) != true)) {
                    this.dblPercentageField = value;
                    this.RaisePropertyChanged("dblPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblToRange {
            get {
                return this.dblToRangeField;
            }
            set {
                if ((this.dblToRangeField.Equals(value) != true)) {
                    this.dblToRangeField = value;
                    this.RaisePropertyChanged("dblToRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.groupNameField, value) != true)) {
                    this.groupNameField = value;
                    this.RaisePropertyChanged("groupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDate {
            get {
                return this.strDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strDateField, value) != true)) {
                    this.strDateField = value;
                    this.RaisePropertyChanged("strDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Division", Namespace="http://schemas.datacontract.org/2004/07/D.API.Model")]
    [System.SerializableAttribute()]
    public partial class Division : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OTP.ISWAPI")]
    public interface ISWAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mobileSMSVerify", ReplyAction="http://tempuri.org/ISWAPI/mobileSMSVerifyResponse")]
        Api.OTP.AppsVercifysumm mobileSMSVerify(string strDeComID, string strMobileNo, string strOTP, string strSIMSL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mobileSMSAPI", ReplyAction="http://tempuri.org/ISWAPI/mobileSMSAPIResponse")]
        string mobileSMSAPI(string strDeComID, string strMobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/DisplayApiChangeOrder", ReplyAction="http://tempuri.org/ISWAPI/DisplayApiChangeOrderResponse")]
        Api.OTP.summaryNew DisplayApiChangeOrder(string strDeComID, string strTc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mGetActive", ReplyAction="http://tempuri.org/ISWAPI/mGetActiveResponse")]
        string mGetActive(string strDeComID, string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadMpoDivisionNew", ReplyAction="http://tempuri.org/ISWAPI/mLoadMpoDivisionNewResponse")]
        Api.OTP.MpoArea[] mLoadMpoDivisionNew(string strDeComID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mUpdateNotification", ReplyAction="http://tempuri.org/ISWAPI/mUpdateNotificationResponse")]
        int mUpdateNotification(string strDeComID, string strDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mGetAppsNotifucation", ReplyAction="http://tempuri.org/ISWAPI/mGetAppsNotifucationResponse")]
        Api.OTP.notification[] mGetAppsNotifucation(string strDeComID, string TC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/UpdateAPISalesOrder", ReplyAction="http://tempuri.org/ISWAPI/UpdateAPISalesOrderResponse")]
        string UpdateAPISalesOrder(string strDeComID, string strSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/DisplayApiOrder", ReplyAction="http://tempuri.org/ISWAPI/DisplayApiOrderResponse")]
        Api.OTP.summaryNew DisplayApiOrder(string strDeComID, string strTc, int intAppSync);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/SaveAPISalesOrder", ReplyAction="http://tempuri.org/ISWAPI/SaveAPISalesOrderResponse")]
        string SaveAPISalesOrder(string strDeComID, string strSummary, string strDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mGetOTPNo", ReplyAction="http://tempuri.org/ISWAPI/mGetOTPNoResponse")]
        string mGetOTPNo(string strDeComID, string strMobileNo, string strTokenNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadStockGroup", ReplyAction="http://tempuri.org/ISWAPI/mLoadStockGroupResponse")]
        Api.OTP.Stockgroup[] mLoadStockGroup(string strDeComID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mGetStockItemFromGroup", ReplyAction="http://tempuri.org/ISWAPI/mGetStockItemFromGroupResponse")]
        Api.OTP.StockItem[] mGetStockItemFromGroup(string strDeComID, string strGroupName, string strBranchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/gstrGetMpoAreaDevisionList", ReplyAction="http://tempuri.org/ISWAPI/gstrGetMpoAreaDevisionListResponse")]
        Api.OTP.MPO gstrGetMpoAreaDevisionList(string strDeComID, string strUserID, string strPassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadCustomerName", ReplyAction="http://tempuri.org/ISWAPI/mLoadCustomerNameResponse")]
        Api.OTP.Customer[] mLoadCustomerName(string strDeComID, string strTc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadItemRate", ReplyAction="http://tempuri.org/ISWAPI/mLoadItemRateResponse")]
        Api.OTP.StockitemRate[] mLoadItemRate(string strDeComID, string strItemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadCommissionSlab", ReplyAction="http://tempuri.org/ISWAPI/mLoadCommissionSlabResponse")]
        Api.OTP.Commissionslab[] mLoadCommissionSlab(string strDeComID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadMpoArea", ReplyAction="http://tempuri.org/ISWAPI/mLoadMpoAreaResponse")]
        Api.OTP.MpoArea[] mLoadMpoArea(string strDeComID, string strDisvion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWAPI/mLoadMpoDivisoin", ReplyAction="http://tempuri.org/ISWAPI/mLoadMpoDivisoinResponse")]
        Api.OTP.Division[] mLoadMpoDivisoin(string strDeComID, string strArea);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWAPIChannel : Api.OTP.ISWAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWAPIClient : System.ServiceModel.ClientBase<Api.OTP.ISWAPI>, Api.OTP.ISWAPI {
        
        public SWAPIClient() {
        }
        
        public SWAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Api.OTP.AppsVercifysumm mobileSMSVerify(string strDeComID, string strMobileNo, string strOTP, string strSIMSL) {
            return base.Channel.mobileSMSVerify(strDeComID, strMobileNo, strOTP, strSIMSL);
        }
        
        public string mobileSMSAPI(string strDeComID, string strMobileNo) {
            return base.Channel.mobileSMSAPI(strDeComID, strMobileNo);
        }
        
        public Api.OTP.summaryNew DisplayApiChangeOrder(string strDeComID, string strTc) {
            return base.Channel.DisplayApiChangeOrder(strDeComID, strTc);
        }
        
        public string mGetActive(string strDeComID, string strName) {
            return base.Channel.mGetActive(strDeComID, strName);
        }
        
        public Api.OTP.MpoArea[] mLoadMpoDivisionNew(string strDeComID, string strDivision) {
            return base.Channel.mLoadMpoDivisionNew(strDeComID, strDivision);
        }
        
        public int mUpdateNotification(string strDeComID, string strDG) {
            return base.Channel.mUpdateNotification(strDeComID, strDG);
        }
        
        public Api.OTP.notification[] mGetAppsNotifucation(string strDeComID, string TC) {
            return base.Channel.mGetAppsNotifucation(strDeComID, TC);
        }
        
        public string UpdateAPISalesOrder(string strDeComID, string strSummary) {
            return base.Channel.UpdateAPISalesOrder(strDeComID, strSummary);
        }
        
        public Api.OTP.summaryNew DisplayApiOrder(string strDeComID, string strTc, int intAppSync) {
            return base.Channel.DisplayApiOrder(strDeComID, strTc, intAppSync);
        }
        
        public string SaveAPISalesOrder(string strDeComID, string strSummary, string strDetails) {
            return base.Channel.SaveAPISalesOrder(strDeComID, strSummary, strDetails);
        }
        
        public string mGetOTPNo(string strDeComID, string strMobileNo, string strTokenNo) {
            return base.Channel.mGetOTPNo(strDeComID, strMobileNo, strTokenNo);
        }
        
        public Api.OTP.Stockgroup[] mLoadStockGroup(string strDeComID) {
            return base.Channel.mLoadStockGroup(strDeComID);
        }
        
        public Api.OTP.StockItem[] mGetStockItemFromGroup(string strDeComID, string strGroupName, string strBranchID) {
            return base.Channel.mGetStockItemFromGroup(strDeComID, strGroupName, strBranchID);
        }
        
        public Api.OTP.MPO gstrGetMpoAreaDevisionList(string strDeComID, string strUserID, string strPassWord) {
            return base.Channel.gstrGetMpoAreaDevisionList(strDeComID, strUserID, strPassWord);
        }
        
        public Api.OTP.Customer[] mLoadCustomerName(string strDeComID, string strTc) {
            return base.Channel.mLoadCustomerName(strDeComID, strTc);
        }
        
        public Api.OTP.StockitemRate[] mLoadItemRate(string strDeComID, string strItemName) {
            return base.Channel.mLoadItemRate(strDeComID, strItemName);
        }
        
        public Api.OTP.Commissionslab[] mLoadCommissionSlab(string strDeComID) {
            return base.Channel.mLoadCommissionSlab(strDeComID);
        }
        
        public Api.OTP.MpoArea[] mLoadMpoArea(string strDeComID, string strDisvion) {
            return base.Channel.mLoadMpoArea(strDeComID, strDisvion);
        }
        
        public Api.OTP.Division[] mLoadMpoDivisoin(string strDeComID, string strArea) {
            return base.Channel.mLoadMpoDivisoin(strDeComID, strArea);
        }
    }
}
